-- Table: public.app_user

-- DROP TABLE IF EXISTS public.app_user;

CREATE TABLE IF NOT EXISTS public.app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    external_user_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk_ljwlj3ck8a4tlv23wdwo8f7hc UNIQUE (external_user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.app_user
    OWNER to francisco;

-- Table: public.cities

-- DROP TABLE IF EXISTS public.cities;

CREATE TABLE IF NOT EXISTS public.cities
(
    id bigint NOT NULL,
    code character varying(255) COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    name character varying(255) COLLATE pg_catalog."default",
    place_id character varying(255) COLLATE pg_catalog."default",
    provider character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cities_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cities
    OWNER to francisco;

-- Table: public.fictions

-- DROP TABLE IF EXISTS public.fictions;

CREATE TABLE IF NOT EXISTS public.fictions
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT fictions_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.fictions
    OWNER to francisco;

-- Table: public.locations

-- DROP TABLE IF EXISTS public.locations;

CREATE TABLE IF NOT EXISTS public.locations
(
    id bigint NOT NULL,
    formatted_address character varying(255) COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    name character varying(255) COLLATE pg_catalog."default",
    place_id character varying(255) COLLATE pg_catalog."default",
    provider character varying(255) COLLATE pg_catalog."default",
    city_id bigint,
    CONSTRAINT locations_pkey PRIMARY KEY (id),
    CONSTRAINT ukh188gxr4tykoyh21bduig8yte UNIQUE (place_id),
    CONSTRAINT fkgvg10vlf7gqvbgf9rbbho3gyg FOREIGN KEY (city_id)
        REFERENCES public.cities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.locations
    OWNER to francisco;

 -- Table: public.scenes

-- DROP TABLE IF EXISTS public.scenes;

CREATE TABLE IF NOT EXISTS public.scenes
(
    id bigint NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    end_at bigint NOT NULL,
    episode_name character varying(255) COLLATE pg_catalog."default",
    episode_number character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    season character varying(255) COLLATE pg_catalog."default",
    segment_type character varying(255) COLLATE pg_catalog."default",
    start_at bigint NOT NULL,
    fiction_id bigint,
    location_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT scenes_pkey PRIMARY KEY (id),
    CONSTRAINT fk5vwdm5v3582cj0whv2n4goje FOREIGN KEY (user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkjb4ucrn5pe7gsxw5u13qo13ta FOREIGN KEY (fiction_id)
        REFERENCES public.fictions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkrd12rc4cmrb2l9h1dmbk12ro6 FOREIGN KEY (location_id)
        REFERENCES public.locations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.scenes
    OWNER to francisco;

-- Table: public.rowapidata

-- DROP TABLE IF EXISTS public.rowapidata;

CREATE TABLE IF NOT EXISTS public.rowapidata
(
    id bigint NOT NULL,
    gmaps text COLLATE pg_catalog."default",
    key character varying(255) COLLATE pg_catalog."default",
    tmdb text COLLATE pg_catalog."default",
    CONSTRAINT rowapidata_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.rowapidata
    OWNER to francisco;


INSERT INTO public.fictions(id, name, type) VALUES (1, '3 days of the condor', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (2, '3 men and a baby', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (3, '12 angry men', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (4, '13 going on 30', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (5, '1408', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (6, '54', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (7, '84 charing cross road', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (8, 'Across 110th street', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (9, 'Adam’s rib', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (10, 'After hours', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (11, 'Alice', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (12, 'Alice in dem städten (alice in the cities)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (13, 'All about eve', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (14, 'All that jazz', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (15, 'Almost famous', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (16, 'Altered states', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (17, 'Amateur', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (18, 'The amazing spider-man', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (19, 'The amazing spider-man 2', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (20, 'The american friend', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (21, 'American gangster', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (22, 'American hustle', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (23, 'American psycho', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (24, 'American splendor', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (25, 'Der amerikanische freund (the american friend)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (26, 'Analyze that', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (27, 'Analyze this', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (28, 'The anderson tapes', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (29, 'Angel heart', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (30, 'Annie hall', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (31, 'Another woman', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (32, 'The apartment', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (33, 'The april fools', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (34, 'Armageddon', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (35, 'Arthur (1981)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (36, 'Arthur (2011)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (37, 'As good as it gets', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (38, 'The avengers (avengers assemble) (2012)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (39, 'Awakenings', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (40, 'Bad lieutenant (1992)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (41, 'Bad timing', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (42, 'Barefoot in the park', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (43, 'Basket case', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (44, 'Batman forever ', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (45, 'The beast from twenty thousand fathoms', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (46, 'A beautiful mind', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (47, 'Being john malkovich', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (48, 'Bell book and candle', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (49, 'Big', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (50, 'The big blue', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (51, 'Big daddy', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (52, 'Birdman', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (53, 'Birth', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (54, 'Black rain', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (55, 'Black swan', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (56, 'Blue jasmine', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (57, 'Boiler room', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (58, 'The bonfire of the vanities', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (59, 'The bourne supremacy', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (60, 'The bourne ultimatum', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (61, 'Breakfast at tiffany’s', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (62, 'Broadway danny rose', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (63, 'Bullets over broadway', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (64, 'Captain america: the first avenger', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (65, 'Carlito’s way', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (66, 'Carnal knowledge', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (67, 'Catch me if you can', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (68, 'Celebrity', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (69, 'Chasing amy', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (70, 'City slickers', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (71, 'Clockers', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (72, 'Closer', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (73, 'Cloverfield', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (74, 'Cocktail', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (75, 'Coming to america', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (76, 'Coogan’s bluff', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (77, 'The cotton club', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (78, 'Crimes and misdemeanors', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (79, 'Crocodile dundee', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (80, 'Cruel intentions', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (81, 'Cruising', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (82, 'Daredevil', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (83, 'The dark knight rises', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (84, 'Death wish', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (85, 'Deep impact', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (86, 'The departed', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (87, 'Desperately seeking susan', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (88, 'The devil wears prada', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (89, 'The devil’s advocate', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (90, 'The dictator', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (91, 'Die hard with a vengeance', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (92, 'Do the right thing', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (93, 'Doctor strange', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (94, 'Dog day afternoon', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (95, 'Donnie brasco', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (96, 'The doors', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (97, 'Dressed to kill', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (98, 'Driller killer', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (99, 'Election', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (100, 'Elf', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (101, 'Enchanted', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (102, 'Entrapment', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (103, 'Escape from new york', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (104, 'Eternal sunshine of the spotless mind', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (105, 'Everyone says i love you', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (106, 'The exorcist', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (107, 'Exorcist ii: the heretic', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (108, 'Fame', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (109, 'Fatal attraction', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (110, 'The first wives club', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (111, 'The fisher king', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (112, 'Frankie and johnny', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (113, 'The french connection', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (114, 'The freshman', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (115, 'Friends with benefits', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (116, 'Funny face', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (117, 'Funny girl', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (118, 'Garden state', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (119, 'Ghost', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (120, 'Ghostbusters', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (121, 'Ghostbusters ii', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (122, 'The godfather', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (123, 'The godfather part ii', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (124, 'The godfather part iii', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (125, 'Godzilla (1998)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (126, 'Goodfellas', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (127, 'The great gatsby (1974)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (128, 'The greatest showman', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (129, 'Gremlins 2: the new batch', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (130, 'Hackers', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (131, 'The heretic: exorcist ii', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (132, 'Hannah and her sisters', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (133, 'Hester street', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (134, 'Highlander', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (135, 'Hitch', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (136, 'Home alone 2: lost in new york', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (137, 'Honeymoon in vegas', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (138, 'The hospital', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (139, 'The hours', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (140, 'The house on 92nd street', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (141, 'How to marry a millionaire', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (142, 'Hudson hawk', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (143, 'The hunger', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (144, 'Husbands and wives', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (145, 'The hustler', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (146, 'I am legend', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (147, 'The ice storm', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (148, 'Independence day', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (149, 'Inside llewyn davis', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (150, 'The irishman', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (151, 'Iron man 2', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (152, 'Jack ryan: shadow recruit', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (153, 'Jerry maguire', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (154, 'John wick', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (155, 'John wick: chapter 2', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (156, 'Johnny suede', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (157, 'Joker', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (158, 'Jungle fever', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (159, 'Kal ho naa ho', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (160, 'Kids', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (161, 'King kong (1933)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (162, 'King kong (1976)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (163, 'The king of comedy', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (164, 'King of new york', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (165, 'A kiss before dying', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (166, 'Kiss of death', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (167, 'Klute', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (168, 'Kramer vs kramer', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (169, 'Last action hero', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (170, 'The last detail', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (171, 'The last house on the left', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (172, 'Léon - the professional ', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (173, 'Letters to juliet', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (174, 'Light sleeper', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (175, 'Limitless', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (176, 'Live and let die', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (177, 'The lost weekend', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (178, 'Love affair (1939)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (179, 'Love affair (1994)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (180, 'Love at first bite', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (181, 'Love story', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (182, 'Made of honor', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (183, 'Madigan', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (184, 'Malcolm x', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (185, 'The man who fell to earth', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (186, 'The manchurian candidate (1962)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (187, 'Manhattan', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (188, 'Manhattan murder mystery', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (189, 'Marathon man', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (190, 'Maximum risk', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (191, 'Mean streets', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (192, 'Meet joe black', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (193, 'Men in black', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (194, 'Men in black ii', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (195, 'Men in black iii', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (196, 'Men in black international', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (197, 'Midnight cowboy', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (198, 'Midnight run', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (199, 'Mighty aphrodite', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (200, 'Miracle on 34th street (1947)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (201, 'Miracle on 34th street (1994)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (202, 'Mr & mrs smith', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (203, 'Mo’ better blues', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (204, 'The money pit', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (205, 'Moonstruck', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (206, 'Munich', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (207, 'My dinner with andre', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (208, 'The naked city', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (209, 'Network', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (210, 'New jack city', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (211, 'New york stories', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (212, 'Nine 1/2 weeks', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (213, 'No way to treat a lady', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (214, 'North by northwest', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (215, 'Nothing sacred', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (216, 'Now you see me', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (217, 'Oblivion', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (218, 'The odd couple', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (219, 'On a clear day you can see forever', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (220, 'On the town', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (221, 'Once upon a time in america', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (222, 'Panic room', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (223, 'The pawnbroker', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (224, 'The pelican brief', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (225, 'Phantom of the paradise', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (226, 'Phone booth', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (227, 'Planes, trains & automobiles', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (228, 'Portrait of jenny', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (229, 'The prisoner of second avenue', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (230, 'Prizzi’s honor', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (231, 'The producers (1967)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (232, 'Q – the winged serpent', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (233, 'Quiz show', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (234, 'Radio days', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (235, 'Raging bull', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (236, 'Ransom', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (237, 'Requiem for a dream', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (238, 'Reversal of fortune', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (239, 'Romancing the stone', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (240, 'Rosemary’s baby', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (241, 'Rounders', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (242, 'The royal tenenbaums', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (243, 'Saboteur', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (244, 'Sabrina (1954)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (245, 'Sabrina (1995)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (246, 'Saturday night fever', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (247, 'Scarface', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (248, 'Scenes from a mall', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (249, 'Scent of a woman', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (250, 'School of rock', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (251, 'Sea of love', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (252, 'Seconds', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (253, 'Serpico', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (254, 'The seven year itch', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (255, 'Sex and the city', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (256, 'Shaft (1971)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (257, 'Shaft (2000)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (258, 'Shame', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (259, 'She’s gotta have it', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (260, 'Sherlock holmes', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (261, 'Sid and nancy', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (262, 'Single white female', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (263, 'Six degrees of separation', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (264, 'Sleepers', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (265, 'Sleepless in seattle', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (266, 'Sliver', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (267, 'Someone to watch over me', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (268, 'Sophie’s choice', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (269, 'Sotto gli occhi dellassassino (aka tenebrae; unsane)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (270, 'Spider-man', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (271, 'Spider-man 2', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (272, 'Spider-man 3', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (273, 'Spider-man: far from home', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (274, 'Spider-man: homecoming', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (275, 'Spider-man: no way home', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (276, 'Splash!', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (277, 'A star is born (2018)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (278, 'Stir crazy', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (279, 'Strangers on a train', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (280, 'Summer of sam', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (281, 'The sunshine boys', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (282, 'Superman', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (283, 'Superman ii', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (284, 'Superman returns', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (285, 'The sweet smell of success', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (286, 'The taking of pelham one two three (1974)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (287, 'The talented mr ripley', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (288, 'Tarzan’s new york adventure', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (289, 'Taxi driver', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (290, 'Tenebrae', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (291, 'That touch of mink', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (292, 'The thomas crown affair (1999)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (293, 'Three days of the condor', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (294, 'Three men and a baby', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (295, 'Tootsie', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (296, 'Topaz', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (297, 'Trading places', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (298, 'Transformers: dark of the moon', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (299, '12 angry men', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (300, 'Under the clock', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (301, 'Unsane', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (302, 'U.s. marshals', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (303, 'The usual suspects', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (304, 'Valley of the dolls', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (305, 'Vanilla sky', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (306, 'The verdict', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (307, 'Vicky cristina barcelona', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (308, 'Wait until dark', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (309, 'Wall street', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (310, 'War of the worlds (2005)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (311, 'The warriors', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (312, 'The way we were', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (313, 'Weekend at bernie’s', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (314, 'West side story (1961)', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (315, 'When harry met sally...', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (316, 'Wolf', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (317, 'The wolf of wall street', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (318, 'Wolfen', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (319, 'Working girl', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (320, 'The wrong man', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (321, 'Year of the dragon', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (322, 'You’ve got mail', 'MOVIE');
INSERT INTO public.fictions(id, name, type) VALUES (323, 'Zoolander', 'MOVIE');

INSERT INTO public.cities(id, code, latitude, longitude, name, place_id, provider) VALUES (1, '10001', 40.7127753, -74.0059728, 'New York', 'ChIJOwg_06VPwokRYv534QaPC8g', 'GOOGLE_MAPS');




--INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (1, '582-598 7th Avenue', 40.75809657351446, -73.98556406181386, 'Times Square', '1', 'GOOGLE_MAPS', 1);

INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (1, 'Manhattan, NY 10036, USA', 40.7579747, -73.9855426,'Times Square' , 'ChIJmQJIxlVYwokRLgeuocVOGVU', 'GOOGLE_MAPS', 1);
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (2, '75 9th Ave, New York, NY 10011, USA', 40.7424396, -74.0061439,'Chelsea Market' , 'ChIJw2lMFL9ZwokRosAtly52YX4', 'GOOGLE_MAPS', 1);
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (3, '4 Pennsylvania Plaza, New York, NY 10001, USA', 40.7505045, -73.9934387,'Madison Square Garden' , 'ChIJhRwB-yFawokR5Phil-QQ3zM', 'GOOGLE_MAPS', 1);
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (4, 'Pier 86, W 46th St, New York, NY 10036, USA', 40.7645266, -73.99960759999999,'Intrepid Sea, Air & Space Museum' , 'ChIJnxlg1U5YwokR8T90UrZiIwI', 'GOOGLE_MAPS', 1);
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (5, '405 Lexington Ave, New York, NY 10174, USA', 40.7516208, -73.97550199999999,'Chrysler Building' , 'ChIJeWPFRwJZwokRGD60OOo74RU', 'GOOGLE_MAPS', 1);
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (6, 'Coney Island, Brooklyn, NY, USA', 40.5755438, -73.9707016,'Coney Island' , 'ChIJy3Wdl0hEwokReRGPPNxadFQ', 'GOOGLE_MAPS', 1);
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (7, '1 E 70th St, New York, NY 10021, USA', 40.7710857, -73.9673861,'Frick Collection' , 'ChIJHRH97uxYwokR6CBeDyn1jtg', 'GOOGLE_MAPS', 1);
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (8, 'Greenwich Village, New York, NY, USA', 40.7335719, -74.0027418,'Greenwich Village' , 'ChIJpxMyDJRZwokRX0XfgiHEgog', 'GOOGLE_MAPS', 1);





INSERT INTO public.app_user(id, name, created_at, email, external_user_id, role, updated_at) VALUES (1, 'Francisco', '2023-07-21 06:49:26.775077+00', 'franciscopossetto@gmail.com', 1, 'ADMIN', '2023-07-21 06:49:26.775077+00');

INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (1, 'Spider-Man squares off against the Rhino and the powerful Electro while struggling to keep his promise to leave Gwen Stacey out of his dangerous life.', 10202, NULL, NULL, 'Times Square Slomo', NULL, 'MINUTE', 05000, 19, 1, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (2,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5278 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4911, 76, 1, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (3,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5799 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4813, 6, 4, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (4,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5210 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4875, 207, 5, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (5,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5418 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4594, 28, 8, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (6,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5439 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4951, 254, 3, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (7,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5660 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4749, 44, 5, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (8,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5884 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4704, 311, 1, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (9,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5593 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4982, 98, 1, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (10,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5238 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4993, 84, 3, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (11,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5418 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4691, 96, 1, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (12,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5332 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4519, 210, 2, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (13,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5398 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4721, 315, 2, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (14,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5662 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4503, 311, 8, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (15,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5707 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4684, 223, 7, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (16,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5549 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4545, 78, 7, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (17,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5079 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4630, 102, 5, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (18,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5258 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4589, 46, 5, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (19,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5414 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4969, 68, 2, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (20,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5269 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4795, 274, 2, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (21,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5623 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4887, 61, 7, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (22,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5559 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4638, 19, 6, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (23,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5888 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4583, 19, 4, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (24,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5059 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4590, 19, 4, 1);
INSERT INTO public.scenes(id, description, end_at, episode_name, episode_number, name, season, segment_type, start_at, fiction_id, location_id, user_id) VALUES (25,'After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.' , 5362 , NULL, NULL, 'spiderman test scene', NULL, 'MINUTE', 4796, 19, 7, 1);
