-- Table: public.app_user

-- DROP TABLE IF EXISTS public.app_user;

CREATE TABLE IF NOT EXISTS public.app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    external_user_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone,
    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk_ljwlj3ck8a4tlv23wdwo8f7hc UNIQUE (external_user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.app_user
    OWNER to francisco;

-- Table: public.cities

-- DROP TABLE IF EXISTS public.cities;

CREATE TABLE IF NOT EXISTS public.cities
(
    id bigint NOT NULL,
    code character varying(255) COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    name character varying(255) COLLATE pg_catalog."default",
    place_id character varying(255) COLLATE pg_catalog."default",
    provider character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cities_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cities
    OWNER to francisco;

-- Table: public.fictions

-- DROP TABLE IF EXISTS public.fictions;

CREATE TABLE IF NOT EXISTS public.fictions
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    img_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT fictions_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.fictions
    OWNER to francisco;

-- Table: public.locations

-- DROP TABLE IF EXISTS public.locations;

CREATE TABLE IF NOT EXISTS public.locations
(
    id bigint NOT NULL,
    formatted_address character varying(255) COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    name character varying(255) COLLATE pg_catalog."default",
    place_id character varying(255) COLLATE pg_catalog."default",
    provider character varying(255) COLLATE pg_catalog."default",
    city_id bigint,
    CONSTRAINT locations_pkey PRIMARY KEY (id),
    CONSTRAINT ukh188gxr4tykoyh21bduig8yte UNIQUE (place_id),
    CONSTRAINT fkgvg10vlf7gqvbgf9rbbho3gyg FOREIGN KEY (city_id)
        REFERENCES public.cities (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.locations
    OWNER to francisco;

 -- Table: public.scenes

-- DROP TABLE IF EXISTS public.scenes;

CREATE TABLE IF NOT EXISTS public.scenes
(
    id bigint NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    end_at bigint NOT NULL,
    episode_name character varying(255) COLLATE pg_catalog."default",
    episode_number character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    season character varying(255) COLLATE pg_catalog."default",
    segment_type character varying(255) COLLATE pg_catalog."default",
    start_at bigint NOT NULL,
    fiction_id bigint,
    location_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT scenes_pkey PRIMARY KEY (id),
    CONSTRAINT fk5vwdm5v3582cj0whv2n4goje FOREIGN KEY (user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkjb4ucrn5pe7gsxw5u13qo13ta FOREIGN KEY (fiction_id)
        REFERENCES public.fictions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkrd12rc4cmrb2l9h1dmbk12ro6 FOREIGN KEY (location_id)
        REFERENCES public.locations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.scenes
    OWNER to francisco;

-- Table: public.rowapidata

-- DROP TABLE IF EXISTS public.rowapidata;

CREATE TABLE IF NOT EXISTS public.rowapidata
(
    id bigint NOT NULL,
    gmaps text COLLATE pg_catalog."default",
    key character varying(255) COLLATE pg_catalog."default",
    tmdb text COLLATE pg_catalog."default",
    CONSTRAINT rowapidata_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.rowapidata
    OWNER to francisco;


INSERT INTO public.fictions(id, name, type, img_url) VALUES (1, '3 days of the condor', 'MOVIE', 'm_3_days_of_the_condor.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (2, '3 men and a baby', 'MOVIE', 'm_3_men_and_a_baby.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (3, '12 angry men', 'MOVIE', 'm_12_angry_men.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (4, '13 going on 30', 'MOVIE', 'm_13_going_on_30.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (5, '1408', 'MOVIE', 'm_1408.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (6, '54', 'MOVIE', 'm_54.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (7, '84 charing cross road', 'MOVIE', 'm_84_charing_cross_road.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (8, 'Across 110th street', 'MOVIE', 'm_across_110th_street.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (9, 'Adam’s rib', 'MOVIE', 'm_adam’s_rib.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (10, 'After hours', 'MOVIE', 'm_after_hours.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (11, 'Alice', 'MOVIE', 'm_alice.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (12, 'Alice in dem städten (alice in the cities)', 'MOVIE', 'm_alice_in_dem_städten_(alice_in_the_cities).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (13, 'All about eve', 'MOVIE', 'm_all_about_eve.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (14, 'All that jazz', 'MOVIE', 'm_all_that_jazz.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (15, 'Almost famous', 'MOVIE', 'm_almost_famous.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (16, 'Altered states', 'MOVIE', 'm_altered_states.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (17, 'Amateur', 'MOVIE', 'm_amateur.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (18, 'The amazing spider-man', 'MOVIE', 'm_the_amazing_spider_man.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (19, 'The amazing spider-man 2', 'MOVIE', 'm_the_amazing_spider_man_2.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (20, 'The american friend', 'MOVIE', 'm_the_american_friend.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (21, 'American gangster', 'MOVIE', 'm_american_gangster.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (22, 'American hustle', 'MOVIE', 'm_american_hustle.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (23, 'American psycho', 'MOVIE', 'm_american_psycho.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (24, 'American splendor', 'MOVIE', 'm_american_splendor.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (25, 'Der amerikanische freund (the american friend)', 'MOVIE', 'm_der_amerikanische_freund_(the_american_friend).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (26, 'Analyze that', 'MOVIE', 'm_analyze_that.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (27, 'Analyze this', 'MOVIE', 'm_analyze_this.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (28, 'The anderson tapes', 'MOVIE', 'm_the_anderson_tapes.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (29, 'Angel heart', 'MOVIE', 'm_angel_heart.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (30, 'Annie hall', 'MOVIE', 'm_annie_hall.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (31, 'Another woman', 'MOVIE', 'm_another_woman.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (32, 'The apartment', 'MOVIE', 'm_the_apartment.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (33, 'The april fools', 'MOVIE', 'm_the_april_fools.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (34, 'Armageddon', 'MOVIE', 'm_armageddon.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (35, 'Arthur (1981)', 'MOVIE', 'm_arthur_(1981).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (36, 'Arthur (2011)', 'MOVIE', 'm_arthur_(2011).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (37, 'As good as it gets', 'MOVIE', 'm_as_good_as_it_gets.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (38, 'The avengers (avengers assemble) (2012)', 'MOVIE', 'm_the_avengers_(avengers_assemble)_(2012).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (39, 'Awakenings', 'MOVIE', 'm_awakenings.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (40, 'Bad lieutenant (1992)', 'MOVIE', 'm_bad_lieutenant_(1992).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (41, 'Bad timing', 'MOVIE', 'm_bad_timing.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (42, 'Barefoot in the park', 'MOVIE', 'm_barefoot_in_the_park.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (43, 'Basket case', 'MOVIE', 'm_basket_case.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (44, 'Batman forever', 'MOVIE', 'm_batman_forever.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (45, 'The beast from twenty thousand fathoms', 'MOVIE', 'm_the_beast_from_twenty_thousand_fathoms.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (46, 'A beautiful mind', 'MOVIE', 'm_a_beautiful_mind.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (47, 'Being john malkovich', 'MOVIE', 'm_being_john_malkovich.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (48, 'Bell book and candle', 'MOVIE', 'm_bell_book_and_candle.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (49, 'Big', 'MOVIE', 'm_big.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (50, 'The big blue', 'MOVIE', 'm_the_big_blue.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (51, 'Big daddy', 'MOVIE', 'm_big_daddy.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (52, 'Birdman', 'MOVIE', 'm_birdman.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (53, 'Birth', 'MOVIE', 'm_birth.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (54, 'Black rain', 'MOVIE', 'm_black_rain.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (55, 'Black swan', 'MOVIE', 'm_black_swan.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (56, 'Blue jasmine', 'MOVIE', 'm_blue_jasmine.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (57, 'Boiler room', 'MOVIE', 'm_boiler_room.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (58, 'The bonfire of the vanities', 'MOVIE', 'm_the_bonfire_of_the_vanities.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (59, 'The bourne supremacy', 'MOVIE', 'm_the_bourne_supremacy.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (60, 'The bourne ultimatum', 'MOVIE', 'm_the_bourne_ultimatum.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (61, 'Breakfast at tiffany’s', 'MOVIE', 'm_breakfast_at_tiffany’s.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (62, 'Broadway danny rose', 'MOVIE', 'm_broadway_danny_rose.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (63, 'Bullets over broadway', 'MOVIE', 'm_bullets_over_broadway.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (64, 'Captain america: the first avenger', 'MOVIE', 'm_captain_america:_the_first_avenger.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (65, 'Carlito’s way', 'MOVIE', 'm_carlito’s_way.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (66, 'Carnal knowledge', 'MOVIE', 'm_carnal_knowledge.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (67, 'Catch me if you can', 'MOVIE', 'm_catch_me_if_you_can.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (68, 'Celebrity', 'MOVIE', 'm_celebrity.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (69, 'Chasing amy', 'MOVIE', 'm_chasing_amy.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (70, 'City slickers', 'MOVIE', 'm_city_slickers.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (71, 'Clockers', 'MOVIE', 'm_clockers.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (72, 'Closer', 'MOVIE', 'm_closer.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (73, 'Cloverfield', 'MOVIE', 'm_cloverfield.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (74, 'Cocktail', 'MOVIE', 'm_cocktail.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (75, 'Coming to america', 'MOVIE', 'm_coming_to_america.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (76, 'Coogan’s bluff', 'MOVIE', 'm_coogan’s_bluff.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (77, 'The cotton club', 'MOVIE', 'm_the_cotton_club.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (78, 'Crimes and misdemeanors', 'MOVIE', 'm_crimes_and_misdemeanors.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (79, 'Crocodile dundee', 'MOVIE', 'm_crocodile_dundee.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (80, 'Cruel intentions', 'MOVIE', 'm_cruel_intentions.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (81, 'Cruising', 'MOVIE', 'm_cruising.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (82, 'Daredevil', 'MOVIE', 'm_daredevil.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (83, 'The dark knight rises', 'MOVIE', 'm_the_dark_knight_rises.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (84, 'Death wish', 'MOVIE', 'm_death_wish.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (85, 'Deep impact', 'MOVIE', 'm_deep_impact.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (86, 'The departed', 'MOVIE', 'm_the_departed.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (87, 'Desperately seeking susan', 'MOVIE', 'm_desperately_seeking_susan.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (88, 'The devil wears prada', 'MOVIE', 'm_the_devil_wears_prada.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (89, 'The devil’s advocate', 'MOVIE', 'm_the_devil’s_advocate.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (90, 'The dictator', 'MOVIE', 'm_the_dictator.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (91, 'Die hard with a vengeance', 'MOVIE', 'm_die_hard_with_a_vengeance.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (92, 'Do the right thing', 'MOVIE', 'm_do_the_right_thing.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (93, 'Doctor strange', 'MOVIE', 'm_doctor_strange.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (94, 'Dog day afternoon', 'MOVIE', 'm_dog_day_afternoon.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (95, 'Donnie brasco', 'MOVIE', 'm_donnie_brasco.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (96, 'The doors', 'MOVIE', 'm_the_doors.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (97, 'Dressed to kill', 'MOVIE', 'm_dressed_to_kill.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (98, 'Driller killer', 'MOVIE', 'm_driller_killer.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (99, 'Election', 'MOVIE', 'm_election.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (100, 'Elf', 'MOVIE', 'm_elf.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (101, 'Enchanted', 'MOVIE', 'm_enchanted.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (102, 'Entrapment', 'MOVIE', 'm_entrapment.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (103, 'Escape from new york', 'MOVIE', 'm_escape_from_new_york.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (104, 'Eternal sunshine of the spotless mind', 'MOVIE', 'm_eternal_sunshine_of_the_spotless_mind.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (105, 'Everyone says i love you', 'MOVIE', 'm_everyone_says_i_love_you.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (106, 'The exorcist', 'MOVIE', 'm_the_exorcist.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (107, 'Exorcist ii: the heretic', 'MOVIE', 'm_exorcist_ii:_the_heretic.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (108, 'Fame', 'MOVIE', 'm_fame.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (109, 'Fatal attraction', 'MOVIE', 'm_fatal_attraction.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (110, 'The first wives club', 'MOVIE', 'm_the_first_wives_club.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (111, 'The fisher king', 'MOVIE', 'm_the_fisher_king.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (112, 'Frankie and johnny', 'MOVIE', 'm_frankie_and_johnny.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (113, 'The french connection', 'MOVIE', 'm_the_french_connection.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (114, 'The freshman', 'MOVIE', 'm_the_freshman.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (115, 'Friends with benefits', 'MOVIE', 'm_friends_with_benefits.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (116, 'Funny face', 'MOVIE', 'm_funny_face.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (117, 'Funny girl', 'MOVIE', 'm_funny_girl.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (118, 'Garden state', 'MOVIE', 'm_garden_state.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (119, 'Ghost', 'MOVIE', 'm_ghost.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (120, 'Ghostbusters', 'MOVIE', 'm_ghostbusters.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (121, 'Ghostbusters ii', 'MOVIE', 'm_ghostbusters_ii.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (122, 'The godfather', 'MOVIE', 'm_the_godfather.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (123, 'The godfather part ii', 'MOVIE', 'm_the_godfather_part_ii.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (124, 'The godfather part iii', 'MOVIE', 'm_the_godfather_part_iii.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (125, 'Godzilla (1998)', 'MOVIE', 'm_godzilla_(1998).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (126, 'Goodfellas', 'MOVIE', 'm_goodfellas.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (127, 'The great gatsby (1974)', 'MOVIE', 'm_the_great_gatsby_(1974).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (128, 'The greatest showman', 'MOVIE', 'm_the_greatest_showman.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (129, 'Gremlins 2: the new batch', 'MOVIE', 'm_gremlins_2:_the_new_batch.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (130, 'Hackers', 'MOVIE', 'm_hackers.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (131, 'The heretic: exorcist ii', 'MOVIE', 'm_the_heretic:_exorcist_ii.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (132, 'Hannah and her sisters', 'MOVIE', 'm_hannah_and_her_sisters.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (133, 'Hester street', 'MOVIE', 'm_hester_street.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (134, 'Highlander', 'MOVIE', 'm_highlander.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (135, 'Hitch', 'MOVIE', 'm_hitch.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (136, 'Home alone 2: lost in new york', 'MOVIE', 'm_home_alone_2:_lost_in_new_york.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (137, 'Honeymoon in vegas', 'MOVIE', 'm_honeymoon_in_vegas.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (138, 'The hospital', 'MOVIE', 'm_the_hospital.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (139, 'The hours', 'MOVIE', 'm_the_hours.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (140, 'The house on 92nd street', 'MOVIE', 'm_the_house_on_92nd_street.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (141, 'How to marry a millionaire', 'MOVIE', 'm_how_to_marry_a_millionaire.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (142, 'Hudson hawk', 'MOVIE', 'm_hudson_hawk.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (143, 'The hunger', 'MOVIE', 'm_the_hunger.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (144, 'Husbands and wives', 'MOVIE', 'm_husbands_and_wives.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (145, 'The hustler', 'MOVIE', 'm_the_hustler.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (146, 'I am legend', 'MOVIE', 'm_i_am_legend.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (147, 'The ice storm', 'MOVIE', 'm_the_ice_storm.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (148, 'Independence day', 'MOVIE', 'm_independence_day.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (149, 'Inside llewyn davis', 'MOVIE', 'm_inside_llewyn_davis.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (150, 'The irishman', 'MOVIE', 'm_the_irishman.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (151, 'Iron man 2', 'MOVIE', 'm_iron_man_2.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (152, 'Jack ryan: shadow recruit', 'MOVIE', 'm_jack_ryan:_shadow_recruit.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (153, 'Jerry maguire', 'MOVIE', 'm_jerry_maguire.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (154, 'John wick', 'MOVIE', 'm_john_wick.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (155, 'John wick: chapter 2', 'MOVIE', 'm_john_wick:_chapter_2.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (156, 'Johnny suede', 'MOVIE', 'm_johnny_suede.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (157, 'Joker', 'MOVIE', 'm_joker.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (158, 'Jungle fever', 'MOVIE', 'm_jungle_fever.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (159, 'Kal ho naa ho', 'MOVIE', 'm_kal_ho_naa_ho.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (160, 'Kids', 'MOVIE', 'm_kids.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (161, 'King kong (1933)', 'MOVIE', 'm_king_kong_(1933).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (162, 'King kong (1976)', 'MOVIE', 'm_king_kong_(1976).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (163, 'The king of comedy', 'MOVIE', 'm_the_king_of_comedy.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (164, 'King of new york', 'MOVIE', 'm_king_of_new_york.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (165, 'A kiss before dying', 'MOVIE', 'm_a_kiss_before_dying.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (166, 'Kiss of death', 'MOVIE', 'm_kiss_of_death.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (167, 'Klute', 'MOVIE', 'm_klute.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (168, 'Kramer vs kramer', 'MOVIE', 'm_kramer_vs_kramer.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (169, 'Last action hero', 'MOVIE', 'm_last_action_hero.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (170, 'The last detail', 'MOVIE', 'm_the_last_detail.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (171, 'The last house on the left', 'MOVIE', 'm_the_last_house_on_the_left.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (172, 'Léon the professional ', 'MOVIE', 'm_léon_the_professional_.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (173, 'Letters to juliet', 'MOVIE', 'm_letters_to_juliet.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (174, 'Light sleeper', 'MOVIE', 'm_light_sleeper.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (175, 'Limitless', 'MOVIE', 'm_limitless.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (176, 'Live and let die', 'MOVIE', 'm_live_and_let_die.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (177, 'The lost weekend', 'MOVIE', 'm_the_lost_weekend.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (178, 'Love affair (1939)', 'MOVIE', 'm_love_affair_(1939).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (179, 'Love affair (1994)', 'MOVIE', 'm_love_affair_(1994).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (180, 'Love at first bite', 'MOVIE', 'm_love_at_first_bite.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (181, 'Love story', 'MOVIE', 'm_love_story.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (182, 'Made of honor', 'MOVIE', 'm_made_of_honor.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (183, 'Madigan', 'MOVIE', 'm_madigan.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (184, 'Malcolm x', 'MOVIE', 'm_malcolm_x.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (185, 'The man who fell to earth', 'MOVIE', 'm_the_man_who_fell_to_earth.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (186, 'The manchurian candidate (1962)', 'MOVIE', 'm_the_manchurian_candidate_(1962).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (187, 'Manhattan', 'MOVIE', 'm_manhattan.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (188, 'Manhattan murder mystery', 'MOVIE', 'm_manhattan_murder_mystery.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (189, 'Marathon man', 'MOVIE', 'm_marathon_man.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (190, 'Maximum risk', 'MOVIE', 'm_maximum_risk.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (191, 'Mean streets', 'MOVIE', 'm_mean_streets.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (192, 'Meet joe black', 'MOVIE', 'm_meet_joe_black.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (193, 'Men in black', 'MOVIE', 'm_men_in_black.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (194, 'Men in black ii', 'MOVIE', 'm_men_in_black_ii.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (195, 'Men in black iii', 'MOVIE', 'm_men_in_black_iii.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (196, 'Men in black international', 'MOVIE', 'm_men_in_black_international.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (197, 'Midnight cowboy', 'MOVIE', 'm_midnight_cowboy.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (198, 'Midnight run', 'MOVIE', 'm_midnight_run.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (199, 'Mighty aphrodite', 'MOVIE', 'm_mighty_aphrodite.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (200, 'Miracle on 34th street (1947)', 'MOVIE', 'm_miracle_on_34th_street_(1947).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (201, 'Miracle on 34th street (1994)', 'MOVIE', 'm_miracle_on_34th_street_(1994).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (202, 'Mr & mrs smith', 'MOVIE', 'm_mr_&_mrs_smith.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (203, 'Mo’ better blues', 'MOVIE', 'm_mo’_better_blues.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (204, 'The money pit', 'MOVIE', 'm_the_money_pit.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (205, 'Moonstruck', 'MOVIE', 'm_moonstruck.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (206, 'Munich', 'MOVIE', 'm_munich.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (207, 'My dinner with andre', 'MOVIE', 'm_my_dinner_with_andre.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (208, 'The naked city', 'MOVIE', 'm_the_naked_city.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (209, 'Network', 'MOVIE', 'm_network.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (210, 'New jack city', 'MOVIE', 'm_new_jack_city.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (211, 'New york stories', 'MOVIE', 'm_new_york_stories.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (212, 'Nine 1/2 weeks', 'MOVIE', 'm_nine_1/2_weeks.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (213, 'No way to treat a lady', 'MOVIE', 'm_no_way_to_treat_a_lady.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (214, 'North by northwest', 'MOVIE', 'm_north_by_northwest.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (215, 'Nothing sacred', 'MOVIE', 'm_nothing_sacred.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (216, 'Now you see me', 'MOVIE', 'm_now_you_see_me.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (217, 'Oblivion', 'MOVIE', 'm_oblivion.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (218, 'The odd couple', 'MOVIE', 'm_the_odd_couple.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (219, 'On a clear day you can see forever', 'MOVIE', 'm_on_a_clear_day_you_can_see_forever.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (220, 'On the town', 'MOVIE', 'm_on_the_town.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (221, 'Once upon a time in america', 'MOVIE', 'm_once_upon_a_time_in_america.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (222, 'Panic room', 'MOVIE', 'm_panic_room.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (223, 'The pawnbroker', 'MOVIE', 'm_the_pawnbroker.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (224, 'The pelican brief', 'MOVIE', 'm_the_pelican_brief.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (225, 'Phantom of the paradise', 'MOVIE', 'm_phantom_of_the_paradise.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (226, 'Phone booth', 'MOVIE', 'm_phone_booth.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (227, 'Planes, trains & automobiles', 'MOVIE', 'm_planes,_trains_&_automobiles.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (228, 'Portrait of jenny', 'MOVIE', 'm_portrait_of_jenny.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (229, 'The prisoner of second avenue', 'MOVIE', 'm_the_prisoner_of_second_avenue.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (230, 'Prizzi’s honor', 'MOVIE', 'm_prizzi’s_honor.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (231, 'The producers (1967)', 'MOVIE', 'm_the_producers_(1967).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (232, 'Q – the winged serpent', 'MOVIE', 'm_q_–_the_winged_serpent.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (233, 'Quiz show', 'MOVIE', 'm_quiz_show.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (234, 'Radio days', 'MOVIE', 'm_radio_days.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (235, 'Raging bull', 'MOVIE', 'm_raging_bull.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (236, 'Ransom', 'MOVIE', 'm_ransom.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (237, 'Requiem for a dream', 'MOVIE', 'm_requiem_for_a_dream.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (238, 'Reversal of fortune', 'MOVIE', 'm_reversal_of_fortune.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (239, 'Romancing the stone', 'MOVIE', 'm_romancing_the_stone.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (240, 'Rosemary’s baby', 'MOVIE', 'm_rosemary’s_baby.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (241, 'Rounders', 'MOVIE', 'm_rounders.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (242, 'The royal tenenbaums', 'MOVIE', 'm_the_royal_tenenbaums.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (243, 'Saboteur', 'MOVIE', 'm_saboteur.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (244, 'Sabrina (1954)', 'MOVIE', 'm_sabrina_(1954).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (245, 'Sabrina (1995)', 'MOVIE', 'm_sabrina_(1995).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (246, 'Saturday night fever', 'MOVIE', 'm_saturday_night_fever.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (247, 'Scarface', 'MOVIE', 'm_scarface.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (248, 'Scenes from a mall', 'MOVIE', 'm_scenes_from_a_mall.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (249, 'Scent of a woman', 'MOVIE', 'm_scent_of_a_woman.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (250, 'School of rock', 'MOVIE', 'm_school_of_rock.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (251, 'Sea of love', 'MOVIE', 'm_sea_of_love.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (252, 'Seconds', 'MOVIE', 'm_seconds.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (253, 'Serpico', 'MOVIE', 'm_serpico.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (254, 'The seven year itch', 'MOVIE', 'm_the_seven_year_itch.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (255, 'Sex and the city', 'MOVIE', 'm_sex_and_the_city.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (256, 'Shaft (1971)', 'MOVIE', 'm_shaft_(1971).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (257, 'Shaft (2000)', 'MOVIE', 'm_shaft_(2000).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (258, 'Shame', 'MOVIE', 'm_shame.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (259, 'She’s gotta have it', 'MOVIE', 'm_she’s_gotta_have_it.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (260, 'Sherlock holmes', 'MOVIE', 'm_sherlock_holmes.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (261, 'Sid and nancy', 'MOVIE', 'm_sid_and_nancy.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (262, 'Single white female', 'MOVIE', 'm_single_white_female.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (263, 'Six degrees of separation', 'MOVIE', 'm_six_degrees_of_separation.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (264, 'Sleepers', 'MOVIE', 'm_sleepers.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (265, 'Sleepless in seattle', 'MOVIE', 'm_sleepless_in_seattle.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (266, 'Sliver', 'MOVIE', 'm_sliver.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (267, 'Someone to watch over me', 'MOVIE', 'm_someone_to_watch_over_me.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (268, 'Sophie’s choice', 'MOVIE', 'm_sophie’s_choice.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (269, 'Sotto gli occhi dellassassino (aka tenebrae; unsane)', 'MOVIE','m_sotto_gli_occhi_dellassassino_(aka_tenebrae;_unsane).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (270, 'Spider-man', 'MOVIE', 'm_spider_man.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (271, 'Spider-man 2', 'MOVIE', 'm_spider_man_2.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (272, 'Spider-man 3', 'MOVIE', 'm_spider_man_3.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (273, 'Spider-man: far from home', 'MOVIE', 'm_spider_man:_far_from_home.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (274, 'Spider-man: homecoming', 'MOVIE', 'm_spider_man:_homecoming.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (275, 'Spider-man: no way home', 'MOVIE', 'm_spider_man:_no_way_home.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (276, 'Splash!', 'MOVIE', 'm_splash!.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (277, 'A star is born (2018)', 'MOVIE', 'm_a_star_is_born_(2018).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (278, 'Stir crazy', 'MOVIE', 'm_stir_crazy.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (279, 'Strangers on a train', 'MOVIE', 'm_strangers_on_a_train.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (280, 'Summer of sam', 'MOVIE', 'm_summer_of_sam.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (281, 'The sunshine boys', 'MOVIE', 'm_the_sunshine_boys.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (282, 'Superman', 'MOVIE', 'm_superman.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (283, 'Superman ii', 'MOVIE', 'm_superman_ii.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (284, 'Superman returns', 'MOVIE', 'm_superman_returns.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (285, 'The sweet smell of success', 'MOVIE', 'm_the_sweet_smell_of_success.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (286, 'The taking of pelham one two three (1974)', 'MOVIE', 'm_the_taking_of_pelham_one_two_three_(1974).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (287, 'The talented mr ripley', 'MOVIE', 'm_the_talented_mr_ripley.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (288, 'Tarzan’s new york adventure', 'MOVIE', 'm_tarzan’s_new_york_adventure.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (289, 'Taxi driver', 'MOVIE', 'm_taxi_driver.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (290, 'Tenebrae', 'MOVIE', 'm_tenebrae.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (291, 'That touch of mink', 'MOVIE', 'm_that_touch_of_mink.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (292, 'The thomas crown affair (1999)', 'MOVIE', 'm_the_thomas_crown_affair_(1999).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (293, 'Three days of the condor', 'MOVIE', 'm_three_days_of_the_condor.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (294, 'Three men and a baby', 'MOVIE', 'm_three_men_and_a_baby.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (295, 'Tootsie', 'MOVIE', 'm_tootsie.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (296, 'Topaz', 'MOVIE', 'm_topaz.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (297, 'Trading places', 'MOVIE', 'm_trading_places.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (298, 'Transformers: dark of the moon', 'MOVIE', 'm_transformers:_dark_of_the_moon.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (299, '12 angry men', 'MOVIE', 'm_12_angry_men.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (300, 'Under the clock', 'MOVIE', 'm_under_the_clock.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (301, 'Unsane', 'MOVIE', 'm_unsane.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (302, 'U.s. marshals', 'MOVIE', 'm_u.s._marshals.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (303, 'The usual suspects', 'MOVIE', 'm_the_usual_suspects.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (304, 'Valley of the dolls', 'MOVIE', 'm_valley_of_the_dolls.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (305, 'Vanilla sky', 'MOVIE', 'm_vanilla_sky.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (306, 'The verdict', 'MOVIE', 'm_the_verdict.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (307, 'Vicky cristina barcelona', 'MOVIE', 'm_vicky_cristina_barcelona.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (308, 'Wait until dark', 'MOVIE', 'm_wait_until_dark.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (309, 'Wall street', 'MOVIE', 'm_wall_street.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (310, 'War of the worlds (2005)', 'MOVIE', 'm_war_of_the_worlds_(2005).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (311, 'The warriors', 'MOVIE', 'm_the_warriors.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (312, 'The way we were', 'MOVIE', 'm_the_way_we_were.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (313, 'Weekend at bernie’s', 'MOVIE', 'm_weekend_at_bernie’s.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (314, 'West side story (1961)', 'MOVIE', 'm_west_side_story_(1961).jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (315, 'When harry met sally...', 'MOVIE', 'm_when_harry_met_sally....jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (316, 'Wolf', 'MOVIE', 'm_wolf.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (317, 'The wolf of wall street', 'MOVIE', 'm_the_wolf_of_wall_street.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (318, 'Wolfen', 'MOVIE', 'm_wolfen.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (319, 'Working girl', 'MOVIE', 'm_working_girl.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (320, 'The wrong man', 'MOVIE', 'm_the_wrong_man.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (321, 'Year of the dragon', 'MOVIE', 'm_year_of_the_dragon.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (322, 'You’ve got mail', 'MOVIE', 'm_you’ve_got_mail.jpg');
INSERT INTO public.fictions(id, name, type, img_url) VALUES (323, 'Zoolander', 'MOVIE', 'm_zoolander.jpg');

INSERT INTO public.cities(id, code, latitude, longitude, name, place_id, provider) VALUES (1, '10001', 40.7127753, -74.0059728, 'New York', 'ChIJOwg_06VPwokRYv534QaPC8g', 'GOOGLE_MAPS');
INSERT INTO public.cities(id, code, latitude, longitude, name, place_id, provider) VALUES (2, '08701', 40.0583238, -74.4056612, 'New Jersey', 'ChIJn0AAnpX7wIkRjW0_-Ad70iw', 'GOOGLE_MAPS');

INSERT INTO public.app_user(id, name, created_at, email, external_user_id, role, updated_at) VALUES (1, 'Francisco Possetto', '2023-07-21 06:49:26.775077+00', 'franciscopossetto@gmail.com', '1ZwcZxlayyL3LYcdXC8kXnE0J4L2', 'ADMIN', '2023-07-21 06:49:26.775077+00');
INSERT INTO public.locations(id, formatted_address, latitude, longitude, name, place_id, provider, city_id) VALUES (1, '199 Market St, Newark, NJ', 40.7354649, -74.1707638,'Market Street' , 'ChIJIcjqdYJTwokRa0ArHlDqxTk', 'GOOGLE_MAPS', 2);
INSERT INTO public.scenes(id, name, description, episode_name, episode_number, season, segment_type, start_at, end_at, fiction_id, location_id, user_id) VALUES (1, 'First scene, Arthur dancing', 'Arthur Fleck dances in a clown costume scene and a group of guys stole their banner', NULL, NULL, NULL, 'MINUTE', 3.23,4.56, 157, 1, 1);
