CREATE TABLE IF NOT EXISTS public.app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    created_at timestamp without time zone,
    email character varying(255) NOT NULL,
    external_user_id character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp without time zone,
    country character varying(255),
    email_verified BOOLEAN,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_external_user_id  UNIQUE (external_user_id)
)